import { Venue } from './venue'

describe('find warehouse space', () => {
	it('should return 0 if there are no availble space', () => {
		const input = [
			'BB',
			'BB',
		]

		const space = Venue.getWarehouseSpace(input)
		expect(space).toBe(0)
	})

	it('warehouse cannot connect to the border', () => {
		const input = [
			'BBB',
			'BCB',
			'BCB',
		]

		const space = Venue.getWarehouseSpace(input)
		expect(space).toBe(0)
	})

	it('warehouse cannot connect to the corridor', () => {
		const input = [
			'BBBB',
			'BCOB',
			'BBBB',
		]

		const space = Venue.getWarehouseSpace(input)
		expect(space).toBe(0)
	})

	it('get maximum warehouse space', () => {
		const input = [
			'BBBBB',
			'BCCDB',
			'BDDDB',
			'BBBBB',
		]

		const space = Venue.getWarehouseSpace(input)
		expect(space).toBe(4)
	})

	it('example 1', () => {
		const input = [
			'BBO',
			'ACB',
			'AAB',
		]

		const space = Venue.getWarehouseSpace(input)
		expect(space).toBe(1)
	})

	it('example 2', () => {
		const input =  [
			'BBBBBBOOOOO',
			'ABADCBOBBBB',
			'ABAADBOBAAB',
			'BBBBBBOBBBB',
		]

		const space = Venue.getWarehouseSpace(input)
		expect(space).toBe(3)
	})

	it.skip('big test', () => {
		const input = [
			'EECBABCEBBBCDBACDEBDCDBECBBCDDAEBCOOCCAEDDDCADAOEOBBCDEDCDDBDODEDEEDDDAECEAECECDCOEBACCDCBCOAE',
			'DCAAADBDCCADCBDOOEBECEBEAOBOADADBBDDCBDEOAEODAECEAAAAODCECBDCDBBOCOCAOODBECBEDDDEDBOCDCBBDBEAD',
			'DCEADCABDCCEEEBEAEBBBAOADOCCBCABEAACODEABADCBBAEDEDBCEDAOBDDBADECAEECCCCABAODEAACDBBCDDABEDABC',
			'ABEBAADCADEODBACDDDAAEABCODCDEBCOADADECCDAOCBBDDEDADBDCCBCAAEBEBOBODDEEBCCBACBCDCDCCAOBABDDDBO',
			'CBBOADDDCABBABEDEBCBDOCBECECECCCCOEACEACCAECOAOABDCEBBOACDEBACCDDBEOCDAEOEOCEEDBOEAACBOEBDBBBD',
			'CDOOEECOAADCEAEEOEBECEEOADDECCDDABEBECBOBCDOBCDDAEBBEEAOBDDDCBBAOBBDODBOBDDCBBBCBAADEEADAADDBC',
			'BDABAACDOCCADDDBBOOADDDCEAADEEEOCAEEOOEDBEAEDCOBOCEACCCCECCOBBCCCEDDEEDOADAABBDADDAEABBBDEODBC',
			'COCOEEABAEOCAEDOECCBBCBCDACEADECOCEBDBBDADABAAACEACBOBCODEAEEABCBBDCEEDOOCDCOACCECEBEDCADCAADE',
			'AOEBBEBBCDBDCDBEECEEOOBBECEDBEEECBABCAEDCCCOCOEAEEBEDECDCBCACOCDEEEOBBDAAAAOCDBADDBCEACEAACBCC',
			'EABDEADECDDCBAEOADECBDDAOAODDBOCDODEAEEOOABOBOAAOEBBCEBDDCOECDACBECEBCDEDDEECCCCEACBCEEECEEEBA',
			'AEDOABEABAOCDAEECEDDEDBDAEDOECAOCCDCEOAECACAEDDADDCAEOAABOBDBEBAEBCCACCAEBCAAOOEEDECEEBDEBCAOD',
			'DDECCCADCBBBBDBBEEEEDAECCCECCACOBDAEECCCDACOCCAACOECBCBBCDCEOADCECAABEABACCAOBEBBBAADECEDADAEO',
			'ABADADDBACCBCABECDDBEADCABACOCCAEEEBEBBAOOAOCECDECABDCCBOEBCACCABBDDCCDACECECABCADEODBADEDBEAA',
			'BCACABCCAAAABBAOAACBBEEDEEAAEBDEECADEBDODAAAEDAACCDEAACADBDABEDEDDOAOODABCADBDAOAAAEAEDCBCEOBA',
			'BDECAEAABCECEBBBCCCACEBADDDBDABBEEEOEBAAAABDCEAEBEEEACABOEDAABDEDOCOCDCCABEDCBAEBDDCDADCDDCBOB',
			'ADACBADAECAAAACCABECAAADEDBDCABACACBCBBEEDOAEEEAADBDEEDAEDCEAACOBBCBBEBBEDAAABEBDBDAEBDDABECAE',
			'AADBEACBOOBEBECBDEEBBCBECCEBCDAAOEDDDEACCODOOCBDEOBABDBBODBABCOBBBADDABACDDBBBCDBCOBACBOBBEEBE',
			'ODCBEBBADBBBCDBBEDCCBODCADBEECBDBDCBEEOAADABBEEOOECDBDCCDBDBDBOCDEBCBEECCAOCEACEBBCDBDCDADBAAB',
			'OCAACDBDACDCDOAEAEAOEDBBECEBBAEEOCAEECDADEDBCCEBEECOABOCOEDABAECEBDABACBBBCDEBCCECCEBDBEODEDCA',
			'CBCDABCDCOABEEEAABAAAEABEEBCDABCBEBBCCCAECCCEACCDECBBCADABDDBECAOBBOCCAEEEEDAOECDDCDCEAEBCAEEC',
			'DBCBAEAAADEBACAEACDAECACEBEEEEEEECCAADDCBCCEADEDDEBBBCEOACCOABAOEEEAEOOAEABEEBEECEEBADECDABBDD',
			'ODDEEBDDDBBABDAOBCCOACCEECBOAADBACCEEBDCBEADCBEACCACEABCDADAOCOBCEEEBDAEEBCCCBBDOOACBCBDEDEDBD',
			'CDODBBOECCEAEBACBBADECBECDEEBDEBBEAADDBCCBEDCEBDABOEDCDCDODOBBCAEAECCBBAAECEOEAACBDEEEADEAOOOC',
			'ODDEDCECDDEBCCEADBEABDOBADDCAEDBAECDEBDDEDEAEDDOBADEBACDABDOCEBBDEBOAEACBBDBBECEDCBBDOOECDADAB',
			'CDEEDDEBEEECBDADCEODCOBDEEBEECCAAODEEDCCEDCAEBBDCBCEDBABADABDDDOACCDOEECDBBEABBACBECAEAAOCECEO',
			'ACEEEDOCCEOACBDACEBODACCCCEADBCBDBOBABACCAODOCDCBDBDEBODBDCECEADBBEOABBBBDDCCCODDEDOCBEAAOCCAA',
			'AEAAOADCAODEAECDEBCDAECCEAOAABCEABBDAOEEABBDEBAODACBBEDCEEABOCDCCADDEAACDBEEDCEBBBEECBBCBDAADD',
			'AEOBCDAEEBCACOOBOBADCAAACBOCBADAEABOBACCOCEAADCCOADOEDBEODBCDACAEECBDDEAACDEECBDECEOCBBEDECEOC',
			'ADDDDCBCABCEABBADEACOAAODBBCBEDBEBACAAECBDAAEAAAECDEBAEBDCAODCBDAEADBAADECCDAACOOOBDCEBCOBDCCC',
			'ABBDCBCEDDEDEEDDEAECBADDBCDBDOBBACBOOEBDEOADEDBBCEDACEDBECCDCAEDEADBBCCBCCDBDACBDBOEDEOEBEAABD',
			'DADEDCADCAOBDCBDEEDAEDDABADCEAOEEADOBAAOABDCEOBBDAEECCCCDEOCODCEEBDDEBDDDACEBBECCCCEECDDOOABCE',
			'BDAAAOCBBOBCBCDBBDODDCACOACACBEAAOACABDBADDECDBAABABBADADECEEEOEEOBBCBACCBBCOAEAEOOBDODDADAAAA',
			'BEOAOACBCCOCBODDBOBEECBBCEECCEDCDACAAOCCCCDEBCAAOAADACEBCACCCEDOADDOCECDCADEEADBEOOODCEEBOECBB',
			'BOCDEAECDDCBCAEBECADADEABBECBAOOCCCDOAEECEECADCEDAADAEOCABDEACBBDCADEOCEDBDBCBEBBBEBADDBBECBCA',
			'BBEEDBCEOCEBCCBEACBEBDDADBDDEBDAADADECADADADDEDDBBADACAAECBDDOAAEECDADEAEBOCBADACAOODECBAEOABB',
			'OCDDCDOEOCBDACDAAACOBBAABBACEADCBCDEDBECCAEBOACEEABECBEOODADDCEBOBDDEBAACEOECBDACDCEABCEBBDOBD',
			'DOECECBBBDCCACOABDDEDDDOAEBBEAEBCDBBCCBEEDDOECCDCBADEBDCCEBOACCDACBACCCAEOBDDDDAEDCBEAECDCEBDB',
			'CAOBAAABEACCEDEDCCAODDADOCODBAAEAAECCCEBBDBCCOCCDBECOEAACEECBAEAEBBBEEAOABEBOAEAAAOADAADDOADDB',
			'DBDAAEDBDEOCOACEOCOEAOEBCDBEEAEDOEBBBAEADOAEEDBOOEBAEACDAEEBCABCADDDDCEAAEBDCOBCBCBBADEAACDAOD',
			'CDBACBACEOCAEBOEBAAAACOABOAAOAOBOAOBEBDBAAEEBBDECACBODCBAEEBCDADABECDEBEACDDCEAADDBDABAAABADOA',
			'ADCAODOADEAAEDCEOACCDADOAAEBCAOCECCDEABACBAACDODCEDCCCDBCEOODACDBBOEEBEDAOBEEDCECBCCCECADODCDO',
			'AEDEBEBCAEBEBDBAEEBCABACBABOBODBBBDAODABDOBBEAEOOCBAECAEBOODCCABDBEAECBEEDCBCABDBCBCCDOBECEDCC',
			'OACEBCACCOADCBCCDAAECBCAECODEACAAOACBDEBABECDDBCDAEAOECDADOEACAEADAABDCCDBOACOOCOBABAOEAECDADD',
			'DCCCBAAOEBDBCDAAECDBEABDDAEODAABBAACBEADADBAABCDCECOOAEOECAEDABDBBABDDCEACCCEDABDDBACEDEEBCEOB',
			'ACDBBDDDBCBCCCBEDCAEAOABACBCECEACECACEDBDACDDBECDDCAOABAECEEBDABAEEABBACEDDDEEOODBDDACOEDDCDEC',
			'EECEDEDEBADABOEEEDAOADEECOOBABCDEDDAEDCEBBEACOEBBEEBODCDDBDACBDCDCEEDECECACAAABEBADCDEBDOBEDBO',
			'EEEDCABACBCDCEECACCBDECOACCEDCBBEADOBAACBCOOBCAOEOBAAAEDEDECDCAEDEDADCOECEBEBCDOBBBAOCDEBCEEBO',
			'EDDEEDOABDDEDEACDADAEDBECOOADBDEDAADBCDEAEOBOAADAOCBBBDOADBBBDEBACACBDCOBEBEDCOOOAEODDAAAEEABC',
			'ADCDBEACDACAABDODOAEDBCCDCADDDEBOEBBEDEDDBCODOOBAODCEDECAABAOECBDODACOCDBEDADOEDAEADCDDCDBDBDO',
			'DBODDCCBDECEABCEODDDOBBOBDECACOCAEOCBAOECDDADEOEBEOCAAAEOAOCBBCOEBDCACEAEBAEADCCDCEDCABBCDODED',
			'EBEOBEDEEODACOBOCAEBOCEBEDEEDBDAAACCBECCOCEDDEODDADCOOBODDACCBAEADBACCEAADBDABOOEBDOAEABCOBECO',
			'BCEODOCDAODDBCDAAEODDEEOCAADADBDBDDEDAAOEACECADEBACEOCBAAEACEOBOEADCDBDDEAABACCCOAECDBEAEAEOAE',
			'DCOBDDDOCCCBDCDCCAADBABADBCBODDEAAADBBEDECCOCECBDDDDOBBEBEBBBCBBADOEACCEBBEBAOBBEOBEEDDCBCABCD',
			'CECBABBABAEEDEACACCEBDEEDBBAAABAEODAAOCCEAEDEEADDCDEEEAECACCCECCEDEODODDBOABBCCDEDECDAAOOBEBDE',
			'BECOCCDBDDCBCOEABOECBAOCACADAAEBDDBBECAECEDBCBDCECABACBABDBOAAABOBOBAABCBEAEDCBACDEAADDBAADAOB',
			'ABOOBBDDBBDDEACEDOCEODAACOEECCDEAACCDDDCBBEBABCBBDEABECEECEDBBDECOAEBCECOEDEDABABBODOEBECBBCAB',
			'DACBDDBACDCOCCEEEECDAEDAOCEBODEODDBBOBEDCEOABBCBBCCADEABCCOAEBABEOAACDDOOECDOCCODCCEOEEAODADAC',
			'AOEAOACDOBABBEOBEDACAODACCBACADDCCDBCEAODBBECEDAOOOCEDCOEAEEEDDAAADBAEODODEDECOABEODBECAEEBDAE',
			'OAAEBDDEAOEEBAEABDCDABEBDBBABCECODEABAEDCCBEAABEBEAECCBDCOCBEAOEBBODBEDDEDDEEOEEADBAEEACCBCDEB',
			'CCAEEEBADAAEBEAEBBCDOEBODOADOBECCDBECODABODBDBADOADDBCEEEDOAEACBCDDBBBOBCBBCECCCOBBCOBEDECECDC',
			'EOBEOOABAOBCAOACDCDEBAEBBAAABABDEACDCEDOBEDECACACACECCODBDBBBOCBAADCODBAACBODDEEOODEAEECCEAABE',
			'DEEEECDEEBCBDBDBDCDABDDAACBEOEEBABCEOBOEBAEOCBBADBBADDADBDBAACECBADCEOEDACCBBBEDAAACDEBBCBCDDD',
			'DBBCBBEACEODECBBBBBABOABBDOABDAABCBCOCCOBECABDCCDABBACABECBACDDCEDDADCEEBAAEAADCCBBAEOCEAODABE',
			'BAEDEEAOBADCAEBDCDEBBEAAEDCBBCBDCEEDCAAECCDDDDDCBDEECBEECBDOEDODEDDAADBOBCDEECBBCEBBACABBOCBEE',
			'CCDCAEAEDCBOEDOODCEEOEBDACEAAADEBBACABODOEDEBECDAECEBEDBBABEBDDCDDOCOOEEECDBDDCCDBOEEEDBCCDAAO',
			'ACCODAEECDABBDABAABDDOCDCBEEAACCDEDCCBCABOOBEDDOCDEDADBDAEAEBBODOEOABDEOECEBBCBDBECCDAEEEAAABE',
			'CDEEDAABEBEECEDCAOEABDBDAAAAEDAEBBCAEEOEBAOOCOBACEAACEEEEBCBEDDBDCEABEECECBOEEEDEACECEABOEDOEE',
			'OOOADEDAECEEDDEDAEAAEBACEOCCAOBDOBCCDCABEOAAOCDAEBDECOAOAECCDDBABODCEBEEDCAECOACBDBAAEECAEDODO',
			'EADDCDCAEEEBCOCCEEDDEBECACEEDAABOEOBDCBBBCBEEDEACECEEAABEDDAEBBCCABBBBECBDEADDECCDCADABCCDDODD',
			'BODOEAOCABCBAECBBEDOABEEDCBEDEDCEAEOCEEBACADEEEBDDBEODECECECDCEEAAOABBDOCADOBCBCCCOCAECAOCCAAC',
			'CACBEDOBCEAABCBDDEECEECDCDADACEEAOAECCEAEBBDBBEBOABBEADADCCCOEBBEEABOBOAECEEAACBAEOBDCOAEADECB',
			'ECDAEDCBEBCDDOCBACBABCBCEEBBECECACBODCDEAAACCEAEEBADBBBODEBECADECBEBDDBBDBDEDBOCEDBADADBCAAEOO',
			'DCBOCBBABAADOBBBADEDEAEOEBADBBEBABAEDBDBCDDCCEADBOCACDADCCABBCCAABBBBACCOCAAOCEDADAECOBAOEACBA',
			'BCOEAODBBDAECAEAAAABDCEAEBCACDAABCBBCBDECAEDAEAOCCBBEDECEEEACBDDBBBDAADBAAADADDDEBBCACEBEDBEOD',
			'DCDBOBAAEDDDEACDADEEECDABBDBCABBDADEDBECOEEOCDCEEBBECABBADACEAEABBOAADCAOCDCAAEBCDDAEOBECBCAAD',
			'CECCBDDDADEDECDCDOOECCCADBBCECEOEDBAADABDOCOBEBCAOACDEDODCCBACCCECOCDADEACAOEABDBBDCBECBAAEACD',
			'OAEBDDDBBBBOEBBECEBADEEDDDADDEBAADDOBOABACCOOBDABAEBACBEEBAOADCAOBDOCCBEDEDEECCBEBEDDBOCOBDADD',
			'OAEOABOCAOOOABCBOEABCCACBBDBCBDACCCCCBCCAOOCCEEAEBEABOCCDCEABDBDECBBEDCBCEBCADACDACAOBEBDCBBAB',
			'DODBAAEEADBEEEEEBEDBEAECCECEBDEBBODCABAAOAAEACCDCEDBBCEBEBCBEECEACBEBBCCOEOODECBBEBEEDBBEDDDCE',
			'OEAOBACACCDEAAEABEDOADBADADAAEBAAAEACAOOABDBAODODAAACABOBDDEBEECCCACECCECEADCDDDEBBBCCACDBECAB',
			'ABAEEEBBACCACDEBBAEEBACBCEAEDODDECABDBDDBEAEDEODCBBADBECCDBCBOOAABOCCOEEBCECCBCDAAOBEADBAEOACC',
			'CABABEOAAEDEDOBEEEDAOEBOECBCCBDDBECEBCCODACCDAEEECEAAEDOAADCDAODADOAEDBADBBBABBOBBBBADAOCCBBOE',
			'BBEADBBBBEDAEBDCAEDCDOAEEEEBCDECBBCADCCCABCOCACAACBOCDADBBEODCOACBAEDEOACADEAOCCDBCDDEOCEADAAA',
			'DCAEDDOEBEDDBDCABCEDEBCAOBCBDBCEBDAEBAEACEADODDCOOOEDEBCOADCBBDCEEABEBADCOAEEBBECBCAOEAEEBBACB',
			'OODBEEDACBBOCABDOEBDDEADOAEDBCDBDDDECCEADCEDBBOOACCBAEOADCDCEEAODAAEOBECAEDAEDACBADBDCDCADEABE',
			'CEACCBDOBEAADBEABBEDEACAEACBODEDEOABDEBCCBADEOCEBBDAOBAEBDEBAECEDAAADOAECBBCEEDABBEOEBBBEEADBC',
			'ECEDOOAAAABODABABAOABACDCBADEAECADBOCBEABCCDAOCAOCDCDBOBAEBCBADDCACEAEEDAEDEDOEAEAECDCDOEADBCB',
			'ABDAAABCADDOEBDCCOCEABCCDDAABEAABBBDECBCBAEECOEAACCDCDBCBDDDCACBOBDABBACDDEBAACECAACDCAADADEAB',
			'CAOBDADEEECADDBECDDDAABDDDEBBBDABACBOBEDDECDDDCECEEOEBEBBBCCEBEDCDDECCCDACCCOCBEAEBADAECCDBAEC',
			'EDOCCDBEDAEBDDDBBODAEBCEOECCEBCCDEEAEACBDBEAACCBDECOEOEAAADOADACDEEECAACBAAEEAEOCACBBBBACAOBCB',
			'EBDEEADECCDBACODBDBBDAOCCECCDAAAEBCDABDEEBCADACDCDAOCBOEDADEOAOEBODEDBDCAEBDDECACADBAAACBCDCED',
			'ABCDAEBACEDEDCBBEBDADACBABEBBBCCECCEDCOEAEAEDDDECBDCDOEOEOBECADDEBBBCCOBDCEBDDEBCCADDAAEEOEBBD',
		]

		const space = Venue.getWarehouseSpace(input)
		expect(space).toBe(9)
	})
})
